server:
  port: 8080

spring:
  application:
    name: RestRastreoIp
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#parametros de servicios externos
external:
  services:
    taxes:
      url: http://data.fixer.io
      apikey: 932f508db423f64299e60a912a6653a3
    ipCountry:
      url: http://api.ipapi.com/
      apikey: 92a132b7deac904f941338d041145e4c
    userCountry:
      url: http://usercountry.agum.com/v1.0/json/
      apikey: 6d12311124f62da02d500edc253da9c7b8322d41b18f1cb7
internal:
  info:
    currency:
      base: USD
    geo:
      destino:
        lat: -34.61315
        lng: -58.37723
      
