INSERT INTO ENC_CLIENTE (CLI_NOMBRE, CLI_IDENTIFICACION ) VALUES   ('Cliente 1', '100000001' );
INSERT INTO ENC_CLIENTE (CLI_NOMBRE, CLI_IDENTIFICACION ) VALUES   ('Cliente 2', '100000002' );
INSERT INTO ENC_CLIENTE (CLI_NOMBRE, CLI_IDENTIFICACION ) VALUES   ('Cliente 3', '100000003' );

INSERT INTO ENC_SERVICIO (SER_NOMBRE, SER_DESCRIPCION ) VALUES   ('Servicio 1', 'venta producto alimentacion' );
INSERT INTO ENC_SERVICIO (SER_NOMBRE, SER_DESCRIPCION ) VALUES   ('Servicio 2', 'venta producto aseo');
INSERT INTO ENC_SERVICIO (SER_NOMBRE, SER_DESCRIPCION ) VALUES   ('Servicio 3', 'venta producto general' );

INSERT INTO ENC_ENCUESTA (ENC_NOMBRE, ENC_ID_CLIENTE, ENC_ID_SERVICIO ) VALUES   ('Encuesta de satisfacción', 1,1 );


INSERT INTO ENC_TIPO_PREGUNTA (TIP_CODIGO, TIP_DESCRIPCION ) VALUES   ('A','Abierta');
INSERT INTO ENC_TIPO_PREGUNTA (TIP_CODIGO, TIP_DESCRIPCION ) VALUES   ('M','Multiple');

INSERT INTO ENC_PREGUNTA (PRE_CODIGO, PRE_TEXTO, PRE_ID_TIPO, PRE_ID_ENCUESTA ) VALUES   ('01', 'cuentenos si le agrado el servicio',1,1 );
INSERT INTO ENC_PREGUNTA (PRE_CODIGO, PRE_TEXTO, PRE_ID_TIPO, PRE_ID_ENCUESTA ) VALUES   ('02', 'califique el servicio',2,1 );
INSERT INTO ENC_PREGUNTA (PRE_CODIGO, PRE_TEXTO, PRE_ID_TIPO, PRE_ID_ENCUESTA ) VALUES   ('03', 'califique los meseros',2,1 );
INSERT INTO ENC_PREGUNTA (PRE_CODIGO, PRE_TEXTO, PRE_ID_TIPO, PRE_ID_ENCUESTA ) VALUES   ('04', 'alguna observacion adicional',1,1 );

INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (2,'MALO');
INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (2,'REGULAR');
INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (2,'BUENO');

INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (3,'1');
INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (3,'2');
INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (3,'3');
INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (3,'4');
INSERT INTO ENC_RESPUESTA_PREGUNTA (RESPRE_ID_PREGUNTA, RESPRE_TEXTO ) VALUES   (3,'5');